belt_reviewer/apps/books_app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'^new/$', views.new, name ='new'),
    url(r'^show/(?P<id>\d+)$', views.show, name = 'show'),
    url(r'^users/(?P<id>\d+)$', views.users, name ='users'),
    url(r'^delete/(?P<id>\d+)$', views.delete, name='delete'),
    url(r'^add_book_review$', views.add_book_review, name='add_book_review'),
    url(r'^add_review$', views.add_review, name ='add_review')
]

belt_reviewer/apps/login_reg_app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name ='index'),
    url(r'^books$', views.success, name='success'),
    url(r'^login$',views.login, name = 'login'),
    url(r'^register$', views.register, name ='register'),
    url(r'^logout$', views.logout, name='logout'),
]

belt_reviewer/belt_reviewer/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.login_reg_app.urls', namespace ='login_reg')),
    url(r'^books/', include('apps.books_app.urls', namespace='books'))
]

belt_reviewer/apps/books_app/models.py
from __future__ import unicode_literals
from ..login_reg_app.models import User
from django.db import models

# Create your models here.
class ReviewManager(models.Manager):
    #This method is used for checking if empty data are sent
    def add_book_review_validations(self, form_data):
        errors = []
        if not form_data['book_title'] or not form_data['review']:
            errors.append('Field must be filled!')
        if form_data['author_id'] == 'None' and not form_data['new_author']:
            errors.append('You must either select an author form list or add new one!')
        if form_data['rating'] == 'None':
            errors.append('You must select a rate number!')
        return errors

    def add_book_review(self, form_data, session_user):
        errors = self.add_book_review_validations(form_data)
        if len(errors)>0:
            # for error in errors:
            #     print error
            return (False, errors)
        else:
            book_title = form_data['book_title']
            review_input = form_data['review']
            rating = form_data['rating']
            this_user_id = session_user['id']

            if form_data['author_id'] != 'None':
                author_input = form_data['author_id']
                # print "Author from selection ", author_input
            else:
                author_input = form_data['new_author']
                # print "Author from input ", author_input

            author = self.create_author(author_input)
            # print "Author: ",author
            book = Book.objects.create(title = book_title, author = author)
            # print "Book :", book
            user = User.objects.get(id = this_user_id)
            # print "This user: ",user
            review = Review.objects.create(review= review_input, rating= rating, book = book, user = user)
            # print "Review: ",review
            return (True, review)

    def create_author(self, data):
        # print "Inside create_author: ",data
        author = Author.objects.create(name=data)
        return author

    def add_review_validations(self, form_data):
        errors = []
        if not form_data['review']:
            errors.append('Field must be filled!')
        elif form_data['rating'] == 'None':
            errors.append('You must select a rate number!')
        return errors

    def add_review(self, data, session_user):
        errors = self.add_review_validations(data)
        if len(errors)>0:
            for error in errors:
                print error
            return (False, errors)
        else:
            book = Book.objects.get(id = data['book_id'])
            this_user_id = session_user['id']
            user = User.objects.get(id = this_user_id)
            in_review = data['review']
            rating = data['rating']
            review = Review.objects.create(review = in_review, rating = rating, book = book, user = user)
            return(True, review)

class Author(models.Model):
    name = models.CharField(max_length=100)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

class Book(models.Model):
    title = models.CharField(max_length=100)
    author = models.ForeignKey(Author)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

class Review(models.Model):
    review = models.TextField()
    rating = models.IntegerField()
    book = models.ForeignKey(Book)
    user = models.ForeignKey('login_reg_app.User')
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

    objects = ReviewManager()

belt_reviewer/apps/books_app/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.contrib import messages

from ..login_reg_app.models import User
from .models import Review, Book
# Create your views here.
def index(request):
    reviews = Review.objects.all().order_by('-id')[:3]
    books = Book.objects.all()
    context = {
        'reviews': reviews,
        'books':books
    }
    return render(request, 'books_app/index.html', context)

def new(request):
    return render(request, 'books_app/new.html')

def add_book_review(request):
    if request.method == 'POST':
        result = Review.objects.add_book_review(request.POST, request.session['user'])
        if not result[0]:
            for error in result[1]:
                messages.error(request, error)
            return redirect(reverse('books:new'))
        else:
            review = result[1]
            # print "Review form result: ",review
            book_id = review.book.id
            # print "Book id ", book_id
            return redirect(reverse('books:show', kwargs ={'id':book_id}))

def show(request, id):
    book = Book.objects.get(id = id)
    # print "Book inside the show method: ",book
    result = Review.objects.filter(book= book)
    # print "Review inside show ",result[0].book.title
    context = {
        'reviews':result
    }
    return render(request, 'books_app/show.html', context)

def add_review(request):
    book_id = request.POST['book_id']
    result = Review.objects.add_review(request.POST, request.session['user'])
    if not result[0]:
        for error in result[1]:
            messages.error(request, error)
    return redirect(reverse('books:show', kwargs ={'id':book_id}))

def users(request,id):
    user = User.objects.get(id=id)
    reviews = Review.objects.filter(user = user)
    count_reviews = Review.objects.filter(user = user).count()
    context = {
        'user':user,
        'reviews':reviews,
        'count_reviews':count_reviews
    }
    return render(request, 'books_app/show_user.html', context)

def delete(request, id):
    book_id = request.POST['book_id']
    Review.objects.filter(id=id).delete()
    return redirect(reverse('books:show', kwargs ={'id':book_id}))

belt_reviewer/apps/books_app/templates/books_app/index.html
<!DOCTYPE html>
<html>
  <head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Books</title>
  </head>
  <body>
    <header>
      <h1>Welcome, {{request.session.user.first_name}} !</h1>
      <div class="header_right">
        <a href="{% url 'books:new' %}">Add Book and Review</a> |
        <a href="{% url 'login_reg:logout' %}">Logout</a>
      </div>
    </header>
    <main>
      <div class="left">
        <h2>Recent Book Reviews:</h2>
        <hr>
        {% for review in reviews %}
            <h4><a href="{% url 'books:show' id=review.book.id %}">{{review.book.title}}</a></h4>
            <h5>Rating: {{review.rating}}</h5>
            <p><a href="{% url 'books:users' id=review.user.id%}">{{review.user.first_name}}</a> says: {{review.review}} </p>
            <p>Posted on {{review.created_at}}</p>
            <hr>
        {% endfor %}
          </div>
        <div >
          <h2>Other Book with Reviews:</h2>
          <div id="recent_books">
            {% for book in books %}
              <a href="{% url 'books:show' id=book.id %}">{{book.title}}</a> <br>
            {% endfor %}
          </div>
        </div>
    </main>
  </body>
</html>

belt_reviewer/apps/books_app/templates/books_app/new.html
<!DOCTYPE html>
<html>
  <head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Book Review</title>
  </head>
  <body>
    <header>
      <div class="header_right">
        <a href="{% url 'books:index' %}">Home</a> |
        <a href="{% url 'login_reg:logout' %}">Logout</a>
      </div>
    </header>
    <h2>Add a New Book Title and a Review:</h2>
    {% if messages %}
      {% for message in messages %}
        <p class="{{message.tags}}">{{message}}</p>
      {% endfor %}
    {% endif %}
    <form action="{% url 'books:add_book_review' %}" method="post">
      {% csrf_token %}
      <label><strong>Book Title</strong></label>
      <input type="text" name="book_title" placeholder='Book Title'> <br>
      <label><strong>Author Name: </strong></label>
              <label>Choose from list:</label>
              <select style="display: inline-block" name="author_id">
                 <option value="None">Select author</option>
                 <option value="Ismaili">Ismaili</option>
              </select> <br>
              <label> Or add a new author: </label>
              <input type="text" name="new_author"> <br>

      <label><strong>Review: </strong></label> <br>
            <textarea name="review" rows="8" cols="80"></textarea> <br>
            <label>Rating:</label>
            <select name="rating">
              <option value="None">Rate</option>
              <option value="1">1</option>
              <option value="2">2</option>
              <option value="3">3</option>
              <option value="4">4</option>
              <option value="5">5</option>
            </select> stars.
      <input type="submit" value="Add Book and Review">
    </form>
  </body>
</html>

belt_reviewer/apps/books_app/templates/books_app/show.html
<!DOCTYPE html>
<html>
  <head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Add a Book Review</title>
  </head>
  <body>
    <header>
      <div class="header_right">
        <a href="{% url 'books:index' %}">Home</a> |
        <a href="{% url 'login_reg:logout' %}">Logout</a>
      </div>
    </header>
    <main>
      <div class="left">
        <p>{{review}}</p>
        <strong><h1>{{reviews.0.book.title}}</h1></strong>
        <h2>Author: {{reviews.0.book.author.name}}</h2>
        <strong><h1>Reviews: </h1></strong>
        <hr>
        {% for review in reviews %}
        <p>
          Rating: {{review.rating}}<br>
          <a href="{% url 'books:users' id=review.user.id %}">{{review.user.first_name}}</a> says: {{review.review}}
          <p>Posted on: {{review.created_at}}</p>
          {% if review.user.id == request.session.user.id %}
          <form  action="{% url 'books:delete' id=review.id %}" method="post">
            {% csrf_token%}
            <input type="hidden" name="book_id" value="{{reviews.0.book.id}}">
            <input type="submit" value="Delete this review">
          </form>
          {% endif %}
        </p>
        <hr>
        {% endfor %}
      </div>
      <div class="right">
        {% if messages %}
          {% for message in messages %}
            <p class="{{message.tags}}">{{message}}</p>
          {% endfor %}
        {% endif %}
        <form action="{% url 'books:add_review' %}" method="post">
          {% csrf_token %}
          <input type="hidden" name="book_id" value="{{reviews.0.book.id}}">
          <h3>Add a Review:</h3>
          <textarea name="review" rows="8" cols="80"></textarea><br>
          Rating:
          <select name="rating">
            <option value="None">Rate</option>
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
            <option value="4">4</option>
            <option value="5">5</option>
          </select> stars
          <input type="submit" value="Submit Review">
        </form>
      </div>
    </main>
  </body>
</html>

belt_reviewer/apps/books_app/templates/books_app/show_user.html
<!DOCTYPE html>
<html>
<head>
  {% load staticfiles %}
  <meta charset="utf-8">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <title>Add a Book Review</title>
</head>
<body>
  <header>
    <div class="header_right">
      <a href="{% url 'books:index' %}">Home</a> |
      <a href="{% url 'books:new' %}">Add Book and Review</a> |
      <a href="{% url 'login_reg:logout' %}">Logout</a>
    </div>
  </header>
  <main>
    <h2>User Alias:</h2>
    <p>
      Name: <strong>{{user.first_name}}</strong><br>
      Email: <strong>{{user.email}}</strong><br>
      Total Reviews: <strong>{{count_reviews}}</strong><br>
    </p>
    <h2>Posted Reviews on the following books:</h2>
    {% for review in reviews %}
      <a href="{% url 'books:show' id=review.book.id %}">{{review.book.title}}</a> <br>
    {% endfor %}

  </main>
</body>
</html>